# This compose file is used to setup 2 dockers
# - one for the database - Postgres 15
# - one for grafana-oss - latest
# The 2 dockers will then be linked together, via a docker network

version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      # Lets use 5430 for the database port
      - 5430:5432

  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS}
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
      GF_DATABASE_HOST: ${GF_DATABASE_HOST}
      GF_DATABASE_PORT: ${GF_DATABASE_PORT}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME}
      GF_DATABASE_USER: ${GF_DATABASE_USER}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data:
    driver: local
  grafana_data:
    driver: local
